name: Kaffy CI (Elixir)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test ${{matrix.otp}} / Elixir  ${{matrix.elixir}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['22', '23', '24', '25']
        elixir: ['1.12.3', '1.13.4', '1.14.5', '1.15.5']
        # Exclude invalid combinations of Elixir and OTP
        exclude:
          - otp: '22'
            elixir: '1.14.5'
          - otp: '22'
            elixir: '1.15.5'
          - otp: '23'
            elixir: '1.15.5'
          - otp: '25'
            elixir: '1.12.3'
          - otp: '25'
            elixir: '1.13.4'
        # Include the release candidate for the next Elixir, but don't
        # fail CI.
        # include:
        #   - elixir: '1.13'
        #     otp: '24'
        #     experimental: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
        otp-version: ${{matrix.otp}} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
