name: Kaffy CI (Elixir 1.10)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test ${{matrix.otp}} / Elixir  ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['21', '22', '23', '24']
        elixir: ['1.10.3', '1.11.4', '1.12']
        # Exclude invalid combinations of Elixir and OTP
        exclude:
          - otp: '21'
            elixir: '1.12'
          - otp: '24'
            elixir: '1.10.3'
        # Include the release candidate for the next Elixir, but don't 
        # fail CI.
        include:
          - elixir: '1.13'
            otp: '24'
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
        otp-version: ${{matrix.otp}} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
